using ModdingAPI;
using HarmonyLib;
using System.IO;
using System;

namespace HugeSilo {
    public class BuildingHugeSilo: ModdedBuilding {
        public BuildingHugeSilo() {
            BuildingHugeSilo.invSize = int.MaxValue;
            BuildingHugeSilo.verboseName = "HugeSilo";
            BuildingHugeSilo.verboseCategory = "Modded";
            BuildingHugeSilo.buildingDef = new BuildingDef {
                isStorage = true,
                usesSharedInventory = false,
                footprintOverride = 1,
                hasItemFilter = true
            };

            this.harmony = new Harmony("com.cerberus1746.huge_silo");
            this.ExecuteHarmony();
        }
    }
    public static class Main {
        public static BuildingHugeSilo hugeSilo;
        public static void Load() {
            Main.hugeSilo = new BuildingHugeSilo();
            using(TextWriter tw = File.CreateText("huge_silo_is_alive.txt")) {
                tw.WriteLine($"Hello! This text file was generated by huge_silo on {DateTime.Now:R}!");

                tw.WriteLine();
                tw.WriteLine("huge_silo also set the following environment variables:");
                tw.WriteLine($"huge_silo_INVOKE_PATH = {Environment.GetEnvironmentVariable("huge_silo_INVOKE_DLL_PATH")}");
                tw.WriteLine($"huge_silo_MANAGED_FOLDER_DIR = {Environment.GetEnvironmentVariable("huge_silo_MANAGED_FOLDER_DIR")}");

                tw.WriteLine("Replace this DLL with a custom-made one to do whatever you want!");

                tw.Flush();
            }
        }
    }
}
